<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hh_http2_push"
 *
 * Auto generated by Extension Builder 2019-05-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['hh_http2_push'] = [
    'title' => 'HTTP/2 Push',
    'description' => 'HTTP/2 Push for TYPO3. Be sure to include extension after scriptmerger if installed. It should be the "last hook". Uses Cookies!',
    'category' => 'misc',
    'author' => 'Christian Hackl',
    'author_email' => 'web@hauer-heinrich.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
    'autoload' => [
        'psr-4' => [
            'HauerHeinrich\\HhHttp2Push\\' => 'Classes'
        ],
    ],
];
